### ISSUE TITLE
Future plans

### ISSUE THREAD

**Issue by gjb2048** [johntron/moodle-theme-selector-block#1]
Hi John,

Do you have plans to maintain this block for M2.9+ as I am considering something similar?

Kind regards,

Gareth

**Comment by johntron** [comment]
@gjb2048 No, sorry. I've changed jobs and am no longer using Moodle.

**Comment by gjb2048** [comment]
Thanks for letting me know :) - was thinking of writing my own but did not want to tread on anybodies toes.

**Comment by johntron** [comment]
Cool, yeah go for it!
